{"name": "test_get_created_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 200)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_users.TestUsers object at 0x000001C2A51FE810>, url_reqres_in = 'https://reqres.in/api'\nfaker = <faker.generator.Generator object at 0x000001C2A52CDA90>\n\n    @pytest.mark.usefixtures(\"created_users\")\n    def test_get_created_user(self, url_reqres_in: str, faker: ModuleType):\n    \n        # Given\n        self.test_create_new_user(url_reqres_in, faker)\n    \n        print(url_reqres_in)\n        url = url_reqres_in + f'/users/{self.created_user_id}'\n        self.logger.info(\n            f'Get created user of id: {self.created_user_id} by get on: {url}')\n        # When\n        response = requests.get(url, headers=self.headers)\n    \n        response_dic = response.json()\n        # Then\n>       assert response.status_code == 200\\\n            and hasattr(response_dic, 'id')\nE       assert (404 == 200)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_users.py:113: AssertionError"}, "attachments": [{"name": "log", "source": "988c8f52-df6b-4ced-8a43-4c2f466d147e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "6da51ad1-02ef-401b-848d-38f6e43100fc-attachment.txt", "type": "text/plain"}], "start": 1678213569599, "stop": 1678213570015, "uuid": "d1c7dbab-e661-4253-9016-d4584ba89712", "historyId": "da0357306ea9568fba78ea9ca2ef9f2a", "testCaseId": "e297dc9d0bd9db3f485a67a39659e19b", "fullName": "tests.test_users.TestUsers#test_get_created_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('created_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "LAPTOP-DKHHR5FU"}, {"name": "thread", "value": "3528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users"}]}