{"name": "Get created user", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 200)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_users.TestUsers object at 0x00000260158D8410>, url_reqres_in = 'https://reqres.in/api'\nfaker = <faker.generator.Generator object at 0x0000026015BA8C10>\n\n    @allure.title(\"Get created user\")\n    @pytest.mark.usefixtures(\"created_users\")\n    def test_get_created_user(self, url_reqres_in: str, faker: ModuleType):\n    \n        # Given\n        self.test_create_new_user(url_reqres_in, faker)\n    \n        print(url_reqres_in)\n        url = url_reqres_in + f'/users/{self.created_user_id}'\n        self.logger.info(\n            f'Get created user of id: {self.created_user_id} by get on: {url}')\n        # When\n        response = requests.get(url, headers=self.headers)\n    \n        response_dic = response.json()\n        # Then\n>       assert response.status_code == 200\\\n            and hasattr(response_dic, 'id')\nE       assert (404 == 200)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_users.py:119: AssertionError"}, "attachments": [{"name": "log", "source": "0cfe28b4-655f-434b-8419-2b92f595ddb2-attachment.txt", "type": "text/plain"}], "start": 1678217398741, "stop": 1678217399115, "uuid": "0f2839f8-7c4e-4404-88e1-4cc66bd6c7b1", "historyId": "da0357306ea9568fba78ea9ca2ef9f2a", "testCaseId": "e297dc9d0bd9db3f485a67a39659e19b", "fullName": "tests.test_users.TestUsers#test_get_created_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('created_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "LAPTOP-DKHHR5FU"}, {"name": "thread", "value": "27080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users"}]}